### ISSUE TITLE
Need way to alter private and protected prop (not getters setters)

### ISSUE THREAD

**Issue by hiraash** [Cinergix/mockgen#6]
Currently its adding the following for a protected variable `interactionCanvas`
```
    public $getInteractionCanvas() {
        return this.$get( 'interactionCanvas' );
    }
    public $createGetterForInteractionCanvas() {
        return this.$createGetterFor( 'interactionCanvas' );
    }
    public $getSpyForInteractionCanvas() {
        return this.$getSpyFor( 'interactionCanvas' );
    }
```
The create spy throws an error because the property does not exist. Altering this and checking it is necessary.

Suggestion: For such cases we can may be simply create a public property with the same name? Will work in runtime.
```
public interactionCanvas;
```

**Comment by thani-sh** [comment]
Fixed with #9
